export interface DailyQuote {
  text: string;
  author: string;
}

/** Curated quotes — one per calendar day, deterministic by date. */
const QUOTES: DailyQuote[] = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese proverb" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "Do not wait to strike till the iron is hot; make it hot by striking.", author: "William Butler Yeats" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Excellence is not a skill. It is an attitude.", author: "Ralph Marston" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "A calm sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher" },
  { text: "Fall seven times, stand up eight.", author: "Japanese proverb" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Why do we fall? So we can learn to pick ourselves up.", author: "Thomas Wayne" },
  { text: "It's not who I am underneath, but what I do that defines me.", author: "Bruce Wayne" },
  { text: "A hero can be anyone, even a man doing something as simple and reassuring as putting a coat around a young boy's shoulders.", author: "Alfred Pennyworth" },
  { text: "Some men aren't looking for anything logical. They can't be bought, bullied, reasoned, or negotiated with.", author: "Alfred Pennyworth" },
  { text: "Why do we fall, sir? So that we can learn to pick ourselves up.", author: "Alfred Pennyworth" },
  { text: "Endure, Master Wayne. Take it. They'll hate you for it, but that's the point of Batman.", author: "Alfred Pennyworth" },
  { text: "Tonight's the night, and it's going to happen again and again. It has to happen.", author: "Alfred Pennyworth" },
  { text: "We burned the forest down to build the manor.", author: "Alfred Pennyworth" },
  { text: "Master Wayne, you haven't been picking up your dry cleaning.", author: "Alfred Pennyworth" },
  { text: "Perhaps both is good.", author: "Alfred Pennyworth" },
  { text: "Very well.", author: "Alfred Pennyworth" },
  { text: "Rise and shine — the day won't organize itself.", author: "Alfred" },
  { text: "A gentleman prepares the night before so the morning belongs to him.", author: "Alfred" },
  { text: "Show up on time. The rest tends to follow.", author: "Alfred" },
  { text: "One task finished beats ten tasks started.", author: "Alfred" },
  { text: "The inbox can wait; your priorities cannot.", author: "Alfred" },
  { text: "Leave early enough to arrive calm.", author: "Alfred" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
  { text: "You have power over your mind—not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "You don't drown by falling in the water; you drown by staying there.", author: "Edwin Louis Cole" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Your limitation—it's only your imagination.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Unknown" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Even the smallest person can change the course of the future.", author: "Galadriel" },
  { text: "There is some good in this world, and it's worth fighting for.", author: "Samwise Gamgee" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "Gandalf" },
  { text: "I will not say: do not weep; for not all tears are an evil.", author: "Gandalf" },
  { text: "It is not the strength of the body that counts, but the strength of the spirit.", author: "J.R.R. Tolkien" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "No one saves us but ourselves.", author: "Buddha" },
  { text: "Today is a good day to have a good day.", author: "Unknown" },
  { text: "Make today so awesome that yesterday gets jealous.", author: "Unknown" },
  { text: "You've got this.", author: "Alfred" },
];

function dayKey(timeZone: string, date = new Date()): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone }).format(date);
}

function hashDay(day: string): number {
  let hash = 0;
  for (let i = 0; i < day.length; i++) {
    hash = (hash * 31 + day.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

/** Returns the same quote all day for a given timezone; changes at local midnight. */
export function getDailyQuote(timeZone: string, date = new Date()): DailyQuote {
  const index = hashDay(dayKey(timeZone, date)) % QUOTES.length;
  return QUOTES[index];
}
